import { TitleEntry } from './types';
import { plainBody } from './summaryFormatters/plain';
import { tableBody } from './summaryFormatters/table';


// To add a new summary format, create a new file in src/summaryFormatters/
// (I suggest copying from table body)
// Import it here and add a corresponding definition below.
// The title is what will appear in the settings menu
export const summaries = {
	plain: {
		title: 'Heading/List',
		func: plainBody,
	},
	table: {
		title: 'Table',
		func: tableBody,
	},
}

// To add a new regex simple define one below
// The title is what will appear in the settings menu
export const regexes = {
	list: {
		title: 'Confluence Style',
		regex: /^\s*- \[ \] @([^\s\/]*).(?:\/\/(\d\d\d\d-\d\d-\d\d) )?([^\n]*)?$/gm,
		query: '/"- [ ] @"',
	},
	link: {
		title: 'Link Style',
		regex: /\[(TODO)\]\((.*?)\)([^\n]+)$/gmi,
		query: '/"[TODO]"',
	},
	plain: {
		title: 'List Style',
		regex: /^\s*- \[ \] ()()([^\n]*)$/gm,
		query: '/"- [ ]"',
	},
}

// Below here is the autogenerated titles that will be used by the settings

function toSettingsTitles(tbl: Record<string, TitleEntry>): Record<string, string> {
	let titles = {};
	for (const [key, value] of Object.entries(tbl)) {
		titles[key] = value.title;
	}

	return titles;
}

export const regexTitles = toSettingsTitles(regexes);
export const summaryTitles = toSettingsTitles(summaries);
