import { TitleEntry } from './types';
import { plainBody, formatTodo as plainFormat } from './summaryFormatters/plain';
import { tableBody, formatTodo as tableFormat } from './summaryFormatters/table';
import { diaryBody, formatTodo as diaryFormat } from './summaryFormatters/diary';

// To add a new summary format, create a new file in src/summaryFormatters/
// (I suggest copying from table body)
// Import it here and add a corresponding definition below.
// The title is what will appear in the settings menu
export const summaries = {
	plain: {
		title: 'Heading/List',
		func: plainBody,
		format: plainFormat,
	},
	table: {
		title: 'Table',
		func: tableBody,
		format: tableFormat,
	},
	diary: {
		title: 'List',
		func: diaryBody,
		format: diaryFormat,
	},
}

// To add a new regex simple define one below
// The title is what will appear in the settings menu
// The regex is what will identify a todo line
// The query is what will identify a note with a todo in it (Joplin search syntax)
// The assignee is a function that extracts the assignee from the todo
// The date is a function that extracts the date from the todo
// The tags is a function that extracts the tags from the todo
// The msg is a function that extracts the message from the todo
// The toggle is an object that containes the [un]completed state of a todo
// The completed_query is what will identify a note with a completed todo (Joplin search syntax)
// The completed_regex is what will identify a line as completed
export const regexes = {
	list: {
		title: 'Confluence Style',
		// change to find completed todo
		regex: /^\s*- \[[ |x]\]\s.*(?<=\s)(?:(@[^\s]+)|(\/\/[^\s]+)|(\+[^\s]+))(?:[^\n]*)?$/gm,
		query: '/"- [ ]"',
		assignee: (todo: string[]) => {
			const result = todo[0].match(/(?<=\s@)([^\s]+)/);
			return result ? result[0] : '';
		},
		date: (todo: string[]) => {
			const result = todo[0].match(/(?<=\s\/\/)([^\s]+)/);
			return result ? result[0] : '';
		},
		tags: (todo: string[]) => {
			// the /g is important to get multiple results instead of a single match
			const result = todo[0].match(/(?<=\s\+)[^\s]+/g);
			return result ? result : [];
		},
		msg: (todo: string[]) => {
			let result = todo[0].split(/\s@[^\s]+/).join('');
			result = result.split(/\s\/\/[^\s]+/).join('');
			result = result.split(/\s\+[^\s]+/).join('');
			result = result.split(/- \[[ |x]\]/).join('');
			return result.trim();
		},
		toggle: { open: '- [ ]', closed: '- [x]' },
		completed_query: '/"- [x]"',
		completed_regex: /^\s*- \[x\]\s.*$/,
	},
	link: {
		title: 'Link Style',
		regex: /\[((?:TODO)|(?:DONE))\]\((.*?)\)([^\n]+)$/gmi,
		query: '/"[TODO]"',
		assignee: (todo: string[]) => { return todo[1]; },
		date: (todo: string[]) => { return todo[2]; },
		tags: (todo: string[]) => { return []; },
		msg: (todo: string[]) => { return todo[3]; },
		toggle: { open: '[TODO]', closed: '[DONE]' },
		completed_query: '/"[DONE]"',
		completed_regex: /\[DONE\]\(.*?\)([^\n]+)$/,
	},
	plain: {
		title: 'List Style',
		regex: /^\s*- \[[ |x]\] ()()([^\n]*)$/gm,
		query: '/"- [ ]"',
		assignee: (todo: string[]) => {
			const result = regexes.list.assignee(todo);
			return result || 'Unassigned';
		},
		date: (todo: string[]) => {
			return regexes.list.date(todo);
		},
		tags: (todo: string[]) => {
			return regexes.list.tags(todo);
		},
		msg: (todo: string[]) => {
			return regexes.list.msg(todo);
		},
		toggle: { open: '- [ ]', closed: '- [x]' },
		completed_query: '/"- [x]"',
		completed_regex: /^\s*- \[x\]\s.*$/,
	},
}

// Below here is the autogenerated titles that will be used by the settings

function toSettingsTitles(tbl: Record<string, TitleEntry>): Record<string, string> {
	let titles = {};
	for (const [key, value] of Object.entries(tbl)) {
		titles[key] = value.title;
	}

	return titles;
}

export const regexTitles = toSettingsTitles(regexes);
export const summaryTitles = toSettingsTitles(summaries);
